version: '3.8'

networks:
  todoapp:
    driver: bridge

services: 
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db
    environment:
      MONGO_INITDB_DATABASE: todo 
    networks:
      - todoapp
  
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - "5027:8080"
    depends_on:
        - mongodb
    networks:
      - todoapp

volumes:
  mongodb: